---
title: "Condtitional Loops"
author: "Scout Leonard"
date: "8/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Task 1
```{r}
pm_2_5 <- 48

if (pm_2_5 < 100) {
  print("Low to moderate risk")
} else if (pm_2_5 >= 100 & pm_2_5 < 150) {
  print("Unhealthy for sensitive groups")
} else {
  print("Health risk present")
}
```

### Task 2

```{r}
species <- c("blue whale")

if (str_detect(species, pattern = "whale")) {
  print("You found a whale!")
}
```

### Task 3

```{r}
max_airtemp_c <- c(24.1)

if (max_airtemp_c > 27){
  print("Temperature too high")
} else if (max_airtemp_c <= 27) {
  print("Temperature ok")
}
```

### Task 4

```{r}
base_burrito <- 6.50

main_ingredient <- "veggie"

if (main_ingredient == "veggie") {
  print(base_burrito)
} else if (main_ingredient == "chicken") {
  print (base_burrito + 3)
} else if (main_ingredient == "steak") {
  print(base_burrito + 3.25)
}
```

## For Loops

### Task 5

```{r}
fish <- c(8, 10, 12, 23)


for (i in seq_along(fish)) {
  proportion_fish = fish[i]/sum(fish)
  print(proportion_fish)
}
```

### Task 6

```{r}
for (i in seq_along(month.name)) {
  print(paste(month.name[i], "is month", i))
}
```

